### ISSUE TITLE
Page Reload and Failed Ajax Post on Button Submit

### ISSUE THREAD

**Issue by agent-reed** [mguida22/wikio-kart#2]

**Comment by agent-reed** [comment]
One clue I found was that with the _Neanderthal_ **->** _Donald Trump_ button we get back a prompt and failed response, however the other two buttons just reload the page.  Tells me that there's something up with the frontend.  Not for nothing, I remember that the bug started coming up as soon as the text field and button design change came into play.....

**Comment by mguida22** [comment]
I'll look into it more sometime this week.

**Comment by mguida22** [comment]
I checked all of the tags and brackets, etc.... I think it may be coming from the form submit. We probably need to do something like this on click

``` js
$('#submit').click(function(event) {
  event.preventDefault();
  // code for ajax
});
```
